package com.cobblemon.mod.common.client.render.item

import java.math.RoundingMode

object PokePuffItemModelRegistry {
    private val modelMap = mapOf(
        "overlay_spicy" to 0.01f,
        "overlay_spicy_only" to 0.02f,
        "overlay_spicy_strawberry" to 0.03f,
        "overlay_dry_only" to 0.04f,
        "overlay_spicy_love" to 0.05f,
        "overlay_sweet_only" to 0.06f,
        "overlay_spicy_berry" to 0.07f,
        "overlay_bitter_only" to 0.08f,
        "overlay_spicy_ribbon" to 0.09f,
        "overlay_sour_only" to 0.10f,
        "overlay_spicy_clover" to 0.11f,
        "overlay_mild_only" to 0.12f,
        "overlay_spicy_flower" to 0.13f,
        "overlay_plain_only" to 0.14f,
        "overlay_spicy_star" to 0.15f,
        "overlay_dry" to 0.16f,
        "overlay_dry_strawberry" to 0.18f,
        "overlay_dry_love" to 0.20f,
        "overlay_dry_berry" to 0.22f,
        "overlay_dry_ribbon" to 0.24f,
        "overlay_dry_clover" to 0.26f,
        "overlay_dry_flower" to 0.28f,
        "overlay_dry_star" to 0.30f,
        "overlay_sweet" to 0.31f,
        "overlay_sweet_strawberry" to 0.33f,
        "overlay_sweet_love" to 0.35f,
        "overlay_sweet_berry" to 0.37f,
        "overlay_sweet_ribbon" to 0.39f,
        "overlay_sweet_clover" to 0.41f,
        "overlay_sweet_flower" to 0.43f,
        "overlay_sweet_star" to 0.45f,
        "overlay_bitter" to 0.46f,
        "overlay_bitter_strawberry" to 0.48f,
        "overlay_bitter_love" to 0.50f,
        "overlay_bitter_berry" to 0.52f,
        "overlay_bitter_ribbon" to 0.54f,
        "overlay_bitter_clover" to 0.56f,
        "overlay_bitter_flower" to 0.58f,
        "overlay_bitter_star" to 0.60f,
        "overlay_sour" to 0.61f,
        "overlay_sour_strawberry" to 0.63f,
        "overlay_sour_love" to 0.65f,
        "overlay_sour_berry" to 0.67f,
        "overlay_sour_ribbon" to 0.69f,
        "overlay_sour_clover" to 0.71f,
        "overlay_sour_flower" to 0.73f,
        "overlay_sour_star" to 0.75f,
        "overlay_mild" to 0.76f,
        "overlay_mild_strawberry" to 0.78f,
        "overlay_mild_love" to 0.80f,
        "overlay_mild_berry" to 0.82f,
        "overlay_mild_ribbon" to 0.84f,
        "overlay_clover" to 0.85f,
        "overlay_mild_clover" to 0.86f,
        "overlay_flower" to 0.87f,
        "overlay_mild_flower" to 0.88f,
        "overlay_star" to 0.89f,
        "overlay_mild_star" to 0.90f,
        "overlay_plain" to 0.91f,
        "overlay_strawberry" to 0.92f,
        "overlay_plain_strawberry" to 0.93f,
        "overlay_love" to 0.94f,
        "overlay_plain_love" to 0.95f,
        "overlay_berry" to 0.96f,
        "overlay_plain_berry" to 0.97f,
        "overlay_ribbon" to 0.98f,
        "overlay_plain_ribbon" to 0.99f
    )

    fun getModelId(key: String): Float {
        return modelMap[key]
            ?.toBigDecimal()?.setScale(2, RoundingMode.HALF_UP)?.toFloat() ?: 0.0f
    }
}